### ISSUE TITLE
Multi-language information

### ISSUE THREAD

**Issue by brusarp** [lolouk44/hassio-addons#39]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

Hi!
I was wandering if is possible to translate all the description from the balance (eg. basal metabolism, visceral fat, lean body mass...).
I can help with italian if you want...

Thank you!

**Comment by brusarp** [comment]
Oh... Okay, no problem... I understand...
I thought it was enough to put placeholders that refer to a file containing the languages ...
I will try to figure out how to translate the json that comes from MQTT 😅

**Comment by lolouk44** [comment]
Check the [doc](https://github.com/lolouk44/hassio-addons/blob/master/mi-scale/DOCS.md)
Basically the key think is:
``` yaml
  - platform: mqtt
    name: "Peso di Brusarp" # <-- place anything you want in here, that's what shows up on HA.
    state_topic: "miscale/USER_NAME/weight" #<-- this won't show up in the front end, so don't worry about translating it
    value_template: "{{ value_json['weight'] }}"
    unit_of_measurement: "kg"
    json_attributes_topic: "miscale/USER_NAME/weight" # <-- this won't show up in the front end, so don't worry about translating it
    icon: mdi:scale-bathroom
```
