### ISSUE TITLE
sensor states stay 'unknown'

### ISSUE THREAD

**Issue by lucifudge** [lolouk44/hassio-addons#47]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
Can't get any data values. I don't see anything via MQTT Explorer, either. Not sure if my Pi4 is even connecting to my scale via btle or not. Also, when I try to put my bt mac address in single quotes and hit save, it removes the single quotes.

**To Reproduce**
rpi4 with hassio and a bluetooth dongle, installed addon, configured and added sensor data and configured addon. restarted HAS.

**Expected behaviour**
no data in sensors, they state unknown

**Screenshots**

**Scale (please complete the following information):**
 - mi scale
 - v2

**Device running Home Assistant (please complete the following information):**
 - pi4 with Mosquitto 
 - usb

**Additional context**
```
# configuration.yaml
sensor:

  - platform: mqtt
    name: "My Weight"
    state_topic: "miscale/Jimmy/weight"
    value_template: "{{ value_json['weight'] }}"
    unit_of_measurement: "Lbs"
    json_attributes_topic: "miscale/Jimmy/weight"
    icon: mdi:scale-bathroom

  - platform: mqtt
    name: "My BMI"
    state_topic: "miscale/Jimmy/weight"
    value_template: "{{ value_json['bmi'] }}"
    icon: mdi:human-pregnant
    unit_of_measurement: "kg/m2"
```
 
addon config:
```
HCI_DEV: hci0
BLUEPY_PASSIVE_SCAN: false
MISCALE_MAC: 5C:CA:D3:EF:11:4B
MQTT_PREFIX: miscale
MQTT_HOST: 127.0.0.1
MQTT_USERNAME: mqtt
MQTT_PASSWORD: password
MQTT_PORT: 1883
TIME_INTERVAL: 30
MQTT_DISCOVERY: true
MQTT_DISCOVERY_PREFIX: homeassistant
USERS:
  - NAME: Jimmy
    SEX: male
    GT: 120
    LT: 150
    HEIGHT: 128
    DOB: '1901-01-01'
```
addon log:
```
-------------------------------------
2021-08-19 04:26:41 - Starting Xiaomi mi Scale...
2021-08-19 04:26:41 - Loading Config From Add-On Options...
2021-08-19 04:26:41 - Config Loaded...
2021-08-19 04:26:41 - Discovery Completed...
```

**Comment by lolouk44** [comment]
Thanks. A few questions:
1) When you step on the scale, do you see anything in the add-on logs? If not you may not have the right MAC address. You can also try to change `BLUEPY_PASSIVE_SCAN` to `true` as this tends to help on RPis
1) Can you see the discovery messages being posted to MQTT to confirm your MQTT connection is correct?

**Comment by lucifudge** [comment]
> 
> 
> Thanks. A few questions:
> 
>     1. When you step on the scale, do you see anything in the add-on logs? If not you may not have the right MAC address. You can also try to change `BLUEPY_PASSIVE_SCAN` to `true` as this tends to help on RPis
> 
>     2. Can you see the discovery messages being posted to MQTT to confirm your MQTT connection is correct?

I see nothing in the logs. I copy and pasted my scales mac address from the mi fit app via clipboard and just reverified.

Changed false to true and restarted addon but still nothing in addon log.

**Comment by lolouk44** [comment]
Make sure you don't have the Mi Fit app open at the same time. You can only have 1 device connected to the scale.
Force kill the Mi Fit app then weigh yourself again

**Comment by lucifudge** [comment]
Disabled Bluetooth on my phone and force quit the app. Power cycled my Pi and reweighed, still nothing in log when I stand on it. Anything else I can try?

**Comment by lolouk44** [comment]
Step on and off the scale to wake it up.

Do you see that MAC address listed if you type `sudo hcitool lescan` in a terminal?
Mine shows up as MIBCS

**Comment by lucifudge** [comment]
```sudo hcitool lescan
hcitool command not found``
Am I able to do that using rpi4 with has os? I used putty to ssh in and it doesn't recognize the command.

Also noticed in my logs for the addon now I'm getting this;

```
2021-08-19 18:58:16 - Bluetooth connection error: Failed to execute management command 'pasvend'
2021-08-19 20:20:05 - Bluetooth connection error: Failed to execute management command 'pasvend'
```

**Comment by lolouk44** [comment]
Since you're using a RPi. are you sure you selected the correct HCI device?
I believe HCI0 will be the RPi's built in BT, and the dongle will be on a different one (most likely HCI1)
Some users reported better stability when disabling the RPI's built-in BT too, so worth a try

**Comment by lucifudge** [comment]
With my usb dongle UNPLUGGED, using hci0 gives me;
```
2021-08-20 21:38:17 - Starting Xiaomi mi Scale...
2021-08-20 21:38:17 - Loading Config From Add-On Options...
2021-08-20 21:38:17 - Config Loaded...
2021-08-20 21:38:17 - Discovery Completed...
2021-08-20 21:38:17 - Bluetooth connection error: Failed to execute management command 'le on' (code: 17, error: Invalid Index)
```

And using hci1 gives me no error, just the normal;
```
2021-08-20 21:37:46 - Starting Xiaomi mi Scale...
2021-08-20 21:37:46 - Loading Config From Add-On Options...
2021-08-20 21:37:46 - Config Loaded...
2021-08-20 21:37:46 - Discovery Completed...
```

With the dongle unplugged and running some bluetoothctl commands in ssh, my scale shows up here;
```
➜  ~ bluetoothctl
Agent registered
[CHG] Controller E4:5F:01:02:51:F1 Pairable: yes
[NEW] Device 7F:D5:0B:8C:19:6F 7F-D5-0B-8C-19-6F
[NEW] Device 5C:CA:D3:EF:11:4B MIBFS
[DEL] Device 7F:D5:0B:8C:19:6F 7F-D5-0B-8C-19-6F
[DEL] Device 5C:CA:D3:EF:11:4B MIBFS
[NEW] Device 5C:CA:D3:EF:11:4B MIBFS
[DEL] Device C4:7C:8D:6C:1C:7E Flower care
[DEL] Device DC:23:4D:3E:F5:52 TY
[DEL] Device 5C:CA:D3:EF:11:4B MIBFS
```

Should I try disabling onboard bluetooth? I'm not sure how to do that. Also, should I have anything in my configuration.yaml related to bluetooth? Should I have a device_tracker snippet such as..?  ;
```
device_tracker:

# BLUETOOTH dongle
  - platform: bluetooth_tracker
    interval_seconds: 60
    device_id: -1
```
