### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by kisjeth** [lolouk44/hassio-addons#92]
ADD-ONS CONFIG:
```
HCI_DEV: hci0
BLUEPY_PASSIVE_SCAN: false
MISCALE_MAC: 0C:95:41:XX:XX:XX
MQTT_PREFIX: miscale
MQTT_HOST: 192.168.1.191
MQTT_USERNAME: XXXXXXXX
MQTT_PASSWORD: XXXXXXXX
MQTT_PORT: 1883
MQTT_RETAIN: true
MQTT_DISCOVERY: true
MQTT_DISCOVERY_PREFIX: homeassistant
MQTT_TLS_CACERTS: Path to CA Cert File
MQTT_TLS_INSECURE: true
DEBUG_LEVEL: INFO
USERS:
  - NAME: Carlo
    SEX: male
    GT: 90
    LT: 110
    HEIGHT: 180
    DOB: "1987-05-25"
  - NAME: Chiara
    SEX: female
    GT: 60
    LT: 89
    HEIGHT: 156
    DOB: "1986-03-02"
  - NAME: Isabella
    SEX: female
    GT: 20
    LT: 59
    HEIGHT: 120
    DOB: "2017-12-19"
  - NAME: Amelia
    SEX: female
    GT: 1
    LT: 19
    HEIGHT: 50
    DOB: "2024-03-21"
```

ADD-ONS LOG: 

2024-06-12 07:07:56 - (INFO) Starting Xiaomi mi Scale v0.3.6...
2024-06-12 07:07:56 - (INFO) Loading Config From Options.json...
2024-06-12 07:07:56 - (INFO) Logging Level Set to INFO...
2024-06-12 07:07:56 - (INFO) Config Loaded...
2024-06-12 07:07:56 - (INFO) MQTT Discovery Setup Completed...
2024-06-12 07:07:56 - (INFO) -------------------------------------
2024-06-12 07:07:56 - (INFO) Initialization completed, step on scale to wake it up and get a weight value sent... Make sure the scale is within reach...

.yaml CONFIG

```
mqtt:
  sensor:
    - name: "Carlo"
      state_topic: "miscale/Carlo/weight"
      value_template: "{{ value_json['weight'] }}"
      unit_of_measurement: "kg"
      json_attributes_topic: "miscale/Carlo/weight"
      icon: mdi:scale-bathroom
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Carlo_Bilancia
    - name: "BMI Carlo"
      state_topic: "miscale/Carlo/weight"
      value_template: "{{ value_json['bmi'] }}"
      icon: mdi:human-pregnant
      unit_of_measurement: "kg/m2"
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Carlo_BMI
    - name: "Chiara"
      state_topic: "miscale/Chiara/weight"
      value_template: "{{ value_json['weight'] }}"
      unit_of_measurement: "kg"
      json_attributes_topic: "miscale/Chiara/weight"
      icon: mdi:scale-bathroom
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Chiara_Bilancia
    - name: "BMI Chiara"
      state_topic: "miscale/Chiara/weight"
      value_template: "{{ value_json['bmi'] }}"
      icon: mdi:human-pregnant
      unit_of_measurement: "kg/m2"
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Chiara_BMI
    - name: "Isabella"
      state_topic: "miscale/Isabella/weight"
      value_template: "{{ value_json['weight'] }}"
      unit_of_measurement: "kg"
      json_attributes_topic: "miscale/Isabella/weight"
      icon: mdi:scale-bathroom
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Isabella_Bilancia
    - name: "BMI Isabella"
      state_topic: "miscale/Isabella/weight"
      value_template: "{{ value_json['bmi'] }}"
      icon: mdi:human-pregnant
      unit_of_measurement: "kg/m2"
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Isabella_BMI
    - name: "Amelia"
      state_topic: "miscale/Amelia/weight"
      value_template: "{{ value_json['weight'] }}"
      unit_of_measurement: "kg"
      json_attributes_topic: "miscale/Amelia/weight"
      icon: mdi:scale-bathroom
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Amelia_Bilancia
    - name: "BMI Amelia"
      state_topic: "miscale/Amelia/weight"
      value_template: "{{ value_json['bmi'] }}"
      icon: mdi:human-pregnant
      unit_of_measurement: "kg/m2"
      # Below lines only needed if long term statistics are required
      state_class: "measurement"
      unique_id: Amelia_BMI
```
 

I am not receiving any data. What am I doing wrong? What am I forgetting?
